apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: todo
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_DB
              value: todo_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
          ports:
            - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: todo
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: aditya81888/todo-app:80310424430ef44c9ded914abdc6a23c9dfe22ae
          imagePullPolicy: IfNotPresent
          env:
            - name: DEBUG
              value: "1"
            - name: ALLOWED_HOSTS
              value: "*"
            - name: DB_NAME
              value: todo_db
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_HOST
              value: db  # This should match the name of the Kubernetes Service for PostgreSQL
            - name: DB_PORT
              value: "5432"
          ports:
            - containerPort: 8000
